M48
; DRILL file {KiCad 7.0.6} date Tue Jul 25 22:23:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-25T22:23:10+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X10.4Y-4.8
X10.4Y-5.0756
T2
X0.9Y-0.9
X0.9Y-5.9
X4.4Y-0.9
X4.5Y-5.9
X10.7Y-5.9
X10.8Y-0.9
T0
M30
